### ISSUE TITLE
Mali bugsi ne štejejo!!!

### ISSUE THREAD

**Issue by MancaKrivec** [JernejHabjan/fuzzy-waddle#132]
Nejko Smejko! 
If I presses a little bugsy, I don't get a pointsy... 🥺

If i get extra motivated, I swipe from right to left (completely accidentally) and I get kocked out of the game!!! 😡

That's all. 
Thank you! 🖤

**Comment by JernejHabjan** [comment]
@MancaKrivec ready for test https://github.com/JernejHabjan/fuzzy-waddle/pull/134 🪰
