### ISSUE TITLE
Higher levels of tiles

### ISSUE THREAD

**Issue by JernejHabjan** [JernejHabjan/fuzzy-waddle#18]
Level 1 and up height
- [x] place tiles manually via code on 2. level and use input to detect if it's clicked
- [x] create editor GUI to specify height of currently added tile (text input with spinner)
- [x] on level 1 and upper, make grid of lines, where tiles can be placed
    https://phaser.io/examples/v3/view/paths/curves/drag-line-curve
- [x] #29
- [x] add support to add second layer in editor (use ramp as walkable)
- [x] #30

**Comment by JernejHabjan** [comment]
I'm helping myself with IsometricWorldToTileXY functions to calculate 2 isometric clickable tile locations, but how can I calculate clickable location for slope like on the right side?
It's currently detected like this (second picture)
![image](https://user-images.githubusercontent.com/21958321/194388617-f56fc8bb-64dd-4b7a-bd6f-51240b369efc.png)
![image](https://user-images.githubusercontent.com/21958321/194388661-9f11f953-2da5-4b26-8333-41c9c4fd802c.png)


answers:
gsoutz — Today at 7:48 PM
calculate based on that sprites position disregard the isometric calculations
photonstorm — Today at 7:54 PM
I agree, set-up a per tile hit zone and use that


point intersection:
https://math.stackexchange.com/a/190373
![image](https://user-images.githubusercontent.com/21958321/194388789-bc70627f-f13e-46e4-b2ed-12a8986f7299.png)

**Comment by jHabjanMXP** [comment]
`(vector from A to M) scalar product (vector from A to B). ....`

vector from A to M is:
`(Xm - Xa), (Ym - Ya)`

dot product between AM and AB:
`AM(x)*AB(x) + AM(y)*AB(y)`

**Comment by jHabjanMXP** [comment]
```javascript
A = {x:32, y:0};
B = {x:64, y: 64 * (1/3)};
C = {x:32, y: 0};
D = {x:0, y: 64 * (2/3)}
const calc=(M)=>{
    AM = {x: M.x - A.x, y: M.y - A.y};
    AB= {x: B.x - A.x, y: B.y-A.y};
    AD = {x: D.x - A.x, y: D.y - A.y};

    AM_skalar_AB = AM.x * AB.x + AM.y * AB.y;
    AM_skalar_AD = AM.x * AD.x + AM.y * AD.y;
    AB_skalar_AB = AB.x * AB.x + AB.y* AB.y;
    AD_skalar_AD = AD.x * AD.x + AD.y * AD.y;

    var in_rectangle = ((0 <= AM_skalar_AB) && (AM_skalar_AB <= AB_skalar_AB)) && ((0<= AM_skalar_AD) && (AM_skalar_AD <= AD_skalar_AD))

    return in_rectangle;
};
console.log(calc({x:32,y:32}),calc({x:64,y:64}))
```

**Comment by JernejHabjan** [comment]
works:
![image](https://user-images.githubusercontent.com/21958321/194612026-354ddda0-dd68-4463-ae92-72516abd0d1e.png)
